### ISSUE TITLE
App Description for Store Listing

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#109]
Write an engaging and informative app description for the store listing on both Google Play Store and Apple App Store. The app description should highlight the unique features, functionalities, and benefits of Resonate, making it appealing to potential users.

**Comment by devmusiczz** [comment]
@chandansgowda assign this task to me.

**Comment by devmusiczz** [comment]
@chandansgowda I have written the short app description according to the requirement. Do i have to raise a pr now?

**Comment by chandansgowda** [comment]
Please create a folder named docs and then inside that a folder named store_listing inside that create a file called description.md

**Comment by NishchayShakya1** [comment]
> Please create a folder named docs and then inside that a folder named store_listing inside that create a file called description.md

I have added the description in my PR #205, please check it.
