### ISSUE TITLE
Design a basic logo and app icon

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#11]
Keeping in mind the colour scheme used by AOSSIE's website, design a basic minimalistic logo and app icon.

**Comment by ALIRAZA17** [comment]
@chandansgowda can you assign this to me?

**Comment by Hbkharsh** [comment]
have created a pr please approve

**Comment by tanishagupta1** [comment]
hey @chandansgowda created a pull request for the same keeping in mind the color scheme, pls review

**Comment by chandansgowda** [comment]
I went through the design. Great job. But I think, the design is too basic and can be improved. Wt do you think @jddeep ?

**Comment by Hbkharsh** [comment]
Chandan why are u being the mentor let the mentor do his work of judging and ordering everyone

**Comment by Hbkharsh** [comment]
In reality you are just ordering everyone for getting your work done and in behalf just asking jaideep for formality

**Comment by chandansgowda** [comment]
Come on @Hbkharsh 
We are all working together. I'm so sorry if u felt bad for my suggestions. We are just getting started to work on the project and I'm just trying to work for the project.
