### ISSUE TITLE
Design Play Store Cover Poster

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#110]
This issue is to create an eye-catching and professional Play Store cover poster for our application. The poster should effectively convey the app's purpose and features while maintaining consistent branding elements.

**Comment by devmusiczz** [comment]
@chandansgowda assign this task to me.

**Comment by shubhalgupta** [comment]
@chandansgowda please assign this task to me

**Comment by chandansgowda** [comment]
Hey @shubhalgupta 
This issue is already assigned to @devmusiczz
