### ISSUE TITLE
Design Play Store Sample Screenshots

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#111]
Design high-quality sample screenshots for Play Store listing. The screenshots should showcase the app's user interface, key functionalities, and various use cases to attract potential users.

**Comment by devmusiczz** [comment]
@chandansgowda assign this task to me.

**Comment by chandansgowda** [comment]
You can take a few sample screenshots from [here](https://github.com/AOSSIE-Org/Resonate/pull/62)

**Comment by devmusiczz** [comment]
@chandansgowda can you please share the font name? also after completing the design , how to share those to you , how will this issue close?

**Comment by chandansgowda** [comment]
Please play around with a few fonts and choose the best one. Look into AOSSIE website's font once. Also add it to docs->store_listing->images-> ADD IMAGES HERE WITH PROPER NAME

**Comment by shubhalgupta** [comment]
Is this issue closed? Or may I start working on it?

**Comment by devmusiczz** [comment]
I'm on it. Everything is ready, I will raise the pr tommorow to close the issue.
