### ISSUE TITLE
Setup app links on iOS

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#117]
Currently, app links work on Android only. This has to be setup on iOS too. Handling of links has been already done. But we still have to setup entitlements on the iOS module. This requires us to host a file on our web server and also have an apple developer account.

**Comment by nick2432** [comment]
can i work on this?

**Comment by chandansgowda** [comment]
Any updates @nick2432 ?

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda  I would like to move forward with this if I get something on the apple developer account as it costs

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
