### ISSUE TITLE
Onboarding screen showing previously filled onboarding form data on consecutive Signed Up 

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#122]
Steps to reproduce:
1. Go to the signup page
2. Create a new account
3. fill onboarding form
4. complete sign up and land on tab view screen (home screen)
5. logout
6. Again navigate to signup page create a new account 
7. Reach the onboarding screen

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda I would like to work on it

**Comment by ashutosh887** [comment]
@Aarush-Acharya 
Let me work on this

**Comment by ashutosh887** [comment]
Please assign @Aarush-Acharya

**Comment by Aarush-Acharya** [comment]
Apologies I cannot assign only  @chandansgowda can do that hey @chandansgowda please do assign this to @ashutosh887

**Comment by chandansgowda** [comment]
@ashutosh887 Any updates ?

**Comment by AKASHANGADII** [comment]
Hey @chandansgowda ,
Can I work on this issue.

**Comment by AKASHANGADII** [comment]
@Aarush-Acharya, I followed the steps that you mentioned. I couldn't find the issue that you have mentioned. Could you please recheck it.

**Comment by Aarush-Acharya** [comment]
@AKASHANGADII  understood will do and will let you know

**Comment by puneethkumar18** [comment]
@Aarush-Acharya  have you checked

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
