### ISSUE TITLE
Create Privacy Policy Document

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#123]
A privacy policy has to be written and hosted as a public resource, which is mandatory for App Store Deployment.

**Comment by ashutosh887** [comment]
Let me work on this @chandansgowda

**Comment by chandansgowda** [comment]
Hey @ashutosh887 
Let me know if you have any queries.

**Comment by ashutosh887** [comment]
Yes I have some queries @chandansgowda

**Comment by chandansgowda** [comment]
@ashutosh887 You can dm me on discord.

**Comment by siddharthbaleja7** [comment]
@chandansgowda  Can you please assign this to me?

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
