### ISSUE TITLE
Need suggestions for marketing Resonate

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#124]
Resonate is getting ready for Beta release and hence we will have to kickstart marketing the same. If you have any suggestions or advice, please add it up in this issue.

**Comment by ashutosh887** [comment]
Let me work on this @chandansgowda

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
