### ISSUE TITLE
Android App links working only on some devices

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#126]

**Comment by akshatbhuhagal** [comment]
Hello @chandansgowda 

I have seen and tested in Android version 10 it's seems working fine for me, I will test it with Android 10+ versions, Can you  please provide some more information related to this issue.

Thanks

**Comment by akshatbhuhagal** [comment]
@chandansgowda please assign this issue to me, Thanks

**Comment by akshatbhuhagal** [comment]
Hello @ShivamMenda 

I'm still working on this issue and it's related to generated shared link of room (group), Suppose I have shared you group link and then on click of that link it has to open on Resonate App but it's not opening for some devices (I have tested around 5-7 devices and it's working for me) I'm still trying to find that bug

**Comment by ShivamMenda** [comment]
@akshatbhuhagal Sure sure 👍

**Comment by chandansgowda** [comment]
Any update ??

**Comment by chsaikumar445** [comment]
is this bug resolved or still open?

**Comment by SharmaDhruv2511** [comment]
@chandansgowda can you please describe the issue what and which link is not working?

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
