### ISSUE TITLE
docs: update readme file

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#135]
The readme file has to be updated. The contribution guidelines have moved to a new file. It has to be removed and new additions like app screenshots etc has to be added. Make the readme look attractive. Also add vercel, livekit and appwrite logo.

**Comment by ShivamMenda** [comment]
Hey @chandansgowda I would like to take this up.

**Comment by chandansgowda** [comment]
Any update on this @ShivamMenda ?

**Comment by ShivamMenda** [comment]
@chandansgowda working on it will finish it by tomorrow night
