### ISSUE TITLE
Error in jump to next screen

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#137]
This error is observed when the app is started and on successful hot restarts.

<img width="1192" alt="Screenshot 2023-09-21 at 8 33 16 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/41890434/a429d7ee-4647-4ebd-ab9c-856f0e4778b8">

**Comment by AKASHANGADII** [comment]
Hey @chandansgowda , can I work on this issue

**Comment by chandansgowda** [comment]
This seems to be an issue with the plugin itself. Will open if its required in the future.
