### ISSUE TITLE
Implement Dynamic Theme Switching Functionality

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#143]
The current application is designed with screens exclusively in dark mode. The objective is to enhance the user experience by implementing a feature that allows users to switch between dark and light themes as per their preference. This issue encompasses the development, integration, and testing of this functionality.

### Acceptance Criteria:

- Users can easily toggle between dark and light themes.
- The selected theme preference persists across app sessions.
- The UI toggle for theme switching is intuitive and visually appealing.
- The feature is thoroughly documented for user understanding.

**Comment by ShivamMenda** [comment]
@chandansgowda I would like to take this up

**Comment by vrundraval24** [comment]
@chandansgowda I would like to make this. 

Approach:
I will create two separate theme modes in the View section...
![Screenshot 2023-09-28 223116](https://github.com/AOSSIE-Org/Resonate/assets/141143426/10c22d0d-9431-422f-bc31-f49454720985)

And will also set colors everywhere dynamically, so any changes would be easier to do...
![Screenshot 2023-09-28 224246](https://github.com/AOSSIE-Org/Resonate/assets/141143426/9b46e0ce-f659-4e06-97e5-e8028183d79f)

I am thinking that I also add a Settings button in the profile screen from which the user will be able to go to settings and there will be a Theme option. 
![profile screen](https://github.com/AOSSIE-Org/Resonate/assets/141143426/9c8a21c8-5307-492c-b188-17f1b3f3c95a)

Or if you want, I can directly add a Theme option to the Profile Screen like this... but I suggest the Settings button
![theme button](https://github.com/AOSSIE-Org/Resonate/assets/141143426/5e6422cb-4326-48c4-a0a4-bf72733f2825)

I am ready from my side with the idea... if you reply then I can start making this right away... 
Thanks 
😃🤝🚀

**Comment by chandansgowda** [comment]
@v

**Comment by vrundraval24** [comment]
Half completed... I wanted to ask... can I modify the dark theme or should I leave it as it is and only add the light theme

**Comment by chandansgowda** [comment]
Feel free to modify the theme if it looks good @vrundraval24
