### ISSUE TITLE
Make it mandatory to verify emails before creating rooms 

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#146]

**Comment by 0xAdiyat** [comment]
@chandansgowda is anyone working on it? If not i'm up for it.

**Comment by 0xAdiyat** [comment]
@chandansgowda thanks for assigning the task to me. Just to clarify one thing, should I allow the user to navigate to the 'create room' screen if their email isn't verified and show them a snackbar saying email is mandatory? Or should we prevent them from navigating to the 'create room' screen and instead show a snackbar saying email verification is mandatory?

**Comment by chandansgowda** [comment]
@0xAdiyat  Don't allow the user to go to create room screen

**Comment by 0xAdiyat** [comment]
> @0xAdiyat Don't allow the user to go to create room screen

okie dokie
