### ISSUE TITLE
Bottom Overflowed while using Split Screen 

### ISSUE THREAD

**Issue by arice77** [AOSSIE-Org/Resonate#152]
Steps to reproduce :
  -Navigate to Sign Up or Login Screen
 -Open Split screen with another app

![lgpg](https://github.com/AOSSIE-Org/Resonate/assets/92450890/31702079-373d-488c-920c-c0847f62823e)
![supg](https://github.com/AOSSIE-Org/Resonate/assets/92450890/5af3e2d2-31a6-4936-a89d-836dfae1b2f5)

**Comment by divyajyotibose** [comment]
Hi. I would like to help. Can you tell me if this problem occurs only in login screen or in other screens too while using split screen?

**Comment by arice77** [comment]
I tried split screen with Login and SignUp Screen and found this error, I did test it with other screens but didn't find any issue yet.

**Comment by arice77** [comment]
> Hi. I would like to help. Can you tell me if this problem occurs only in login screen or in other screens too while using split screen?


I tried split screen with Login and SignUp Screen and found this error, I did test it with other screens but didn't find any issue yet.
