### ISSUE TITLE
Design Enhancement and Ideas Figma Board

### ISSUE THREAD

**Issue by notpritam** [AOSSIE-Org/Resonate#159]
**Suggestion**
 To streamline the designing process and gather creative input, we should create a Figma board for design ideas and improvements. 
that will help us gather more ideas around design changes and we can even create design prototypes there. 
Let's collaborate to make our project's design even better!

Would love to create the board also, if i got the chance and we can link that board link to docs for easy access for new users.

**Comment by chandansgowda** [comment]
Great idea @notpritam

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
