### ISSUE TITLE
Implement Push notifications as reminders to create a room.

### ISSUE THREAD

**Issue by ShivamMenda** [AOSSIE-Org/Resonate#168]
This issue is an enhancement to the user experience, where we can keep a separate reminder tab so that the user can log the topic and the time he/she needs to speak on a topic. A push notification will be sent at that time with the topic name reminding the user. This reminder tab can be later extended to scheduling a room similar to issue #97. 

@chandansgowda This issue might take a bit longer, but good for enhancing user experience. Can I work on this?

**Comment by ShivamMenda** [comment]
@chandansgowda I would suggest a local push notification approach, but if it is possible to do it using appwrite we can explore those options too.

**Comment by Aarush-Acharya** [comment]
Hey @ShivamMenda this is similar to the discussions tab please let me work on this one 

Also I wanted to discuss on push notifications as in how do we plan to implement them, we can use a push notification provider like pushy or there is on option of using Firebase FCM

**Comment by ShivamMenda** [comment]
@Aarush-Acharya Maybe we could work together? Me on the notifications and you on the scheduled discussions? There's always an option to co-commit 2 authors.

**Comment by Aarush-Acharya** [comment]
@ShivamMenda  Alright Understood
