### ISSUE TITLE
Add Supporting docs to match community guidelines.

### ISSUE THREAD

**Issue by ShivamMenda** [AOSSIE-Org/Resonate#173]
@chandansgowda The following templates still need to be added as per GitHub community guidelines.  
<img width="891" alt="Screenshot 2023-10-06 at 11 03 21 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/74780977/ec1651dc-307c-48f1-aaf6-36445c7b0f25">

I would like to add the templates one by one as part of documentation to enhance the project.

**Comment by chandansgowda** [comment]
Any updates @ShivamMenda ?

**Comment by ShivamMenda** [comment]
@chandansgowda working on it!

**Comment by ShivamMenda** [comment]
@chandansgowda Opened a PR please check.
