### ISSUE TITLE
ui: improve pair chat screen design

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#174]
The current pair chat screen looks so plain and basic. Improve it by adding more elements and rearranging the current widget tree.

**Comment by bhoomikshetty** [comment]
Hey, @chandansgowda can you assign this task to me.

**Comment by hrushikeshhd18** [comment]
Hey can u assign this to me..?

**Comment by ThienNg65** [comment]
Can you please assign me to this issue?

**Comment by chandansgowda** [comment]
Any update @hrushikeshhd18 ?

**Comment by hrushikeshhd18** [comment]
yes have done it will take a pull request in today

**Comment by ThienNg65** [comment]
@chandansgowda Can you check my pull request?

**Comment by narasimha-1511** [comment]
can you assign me this issue

**Comment by tanyas-codes** [comment]
@chandansgowda is this issue still open to contribute to?

**Comment by chandansgowda** [comment]
@tanyas-codes @narasimha-1511 Are you from codepeak ?

**Comment by Touseef-md** [comment]
Hey, @chandansgowda I would like to contribute,if none are available. I'm a participant of codepak23

**Comment by narasimha-1511** [comment]
@chandansgowda no bro

**Comment by TheGuyDangerous** [comment]
@chandansgowda is this issue still open to contribute to?(not from codepeak, just a regular contributor)

**Comment by puneethkumar18** [comment]
I would like work on this 
Pls assign this to me

**Comment by TheGuyDangerous** [comment]
hi  @puneethkumar18 , i have already started working on this. I'll let you know if I face any problems.

**Comment by puneethkumar18** [comment]
@TheGuyDangerous still are you working ??

**Comment by TheGuyDangerous** [comment]
@puneethkumar18 yes, I am

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
