### ISSUE TITLE
Missing redirect Url in Oauth 

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#185]
<img width="366" alt="Screenshot 2023-10-10 at 6 46 11 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/92685647/164434ee-5044-49c9-9b80-e38c2b3a8901">

Appwrite Oauth both for google and github after signIn successful does not redirect to the app it shows missing redirect Url on the web

**Comment by vrundraval24** [comment]
@chandansgowda 
I want to work on this issue. I kind of solved this issue already... just left to raise a PR, if you assign me.
if @Aarush-Acharya is ok with me working on this issue. Aarush pls reply if it's OK or Not.

**Comment by Aarush-Acharya** [comment]
Sure, go ahead
