### ISSUE TITLE
Filter rooms by tag in room list 

### ISSUE THREAD

**Issue by ShivamMenda** [AOSSIE-Org/Resonate#188]
This feature allows users to filter the rooms displayed on the home screen based on the tags assigned. 
@chandansgowda I would like to work on this feature.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
