### ISSUE TITLE
Finalize Firebase Firestore Structure

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#19]
Here is a basic idea of how we can structure the Firestore database. Let's discuss and come to a final structure before implementing the same.
<br>
![firebase](https://user-images.githubusercontent.com/41890434/226342469-28b8c27b-7013-41f1-9c7e-a5903b8bba56.png)

**Comment by AntoTomAbraham** [comment]
> Here is a basic idea of how we can structure the Firestore database. Let's discuss and come to a final structure before implementing the same. ![firebase](https://user-images.githubusercontent.com/41890434/226342469-28b8c27b-7013-41f1-9c7e-a5903b8bba56.png)

We should also have clubID as an attribute in the spaces collection, like under which club this particular Space comes

**Comment by Axhaat** [comment]
@AntoTomAbraham 
Do you mean something like **RoomID** (generated based on its specifications)?

**Comment by AntoTomAbraham** [comment]
> @AntoTomAbraham Do you mean something like **RoomID** (generated based on its specifications)?

No, **ClubID** is different, a club refers to a group within the app that has a specific focus or theme and it would be made by users only, so here actually we need to give under which group this space comes. we can also have an option where people can host space independently without any club.

**Comment by chandansgowda** [comment]
Yeahh @AntoTomAbraham . Seems right. Like club can be renamed as organizations ? If I'm not wrong ?

**Comment by chandansgowda** [comment]
Hey @AntoTomAbraham 
Using the fields you have suggested, how will the Firebase structure look like ?

**Comment by AntoTomAbraham** [comment]
<img width="739" alt="Capture" src="https://user-images.githubusercontent.com/64683098/227791997-591fd6cd-7a16-4caf-aa25-21f4404e5d9c.PNG">

**Comment by Axhaat** [comment]
@chandansgowda can't we include a field that would store the chat history of the room, in case they want to get back to it in the future?

**Comment by chandansgowda** [comment]
Yeahh @Axhaat We will have to store that too if we are including chat option. But as of now, the main motto is to get the project up and running with atleast some main features. We can keep that for the future.

**Comment by mmjsmohit** [comment]
@chandansgowda As cited in [this](https://firebase.google.com/docs/firestore/manage-data/enable-offline) link, offline persistence is enabled by default in Firestore database for Android and iOS. Thus, Firestore is fundamentally more bandwidth-saving as compared to Realtime Database.

**Comment by chandansgowda** [comment]
This issue is no longer needed since we have migrated our project from Firebase to Appwrite.
