### ISSUE TITLE
AuthenticationController not found. 

### ISSUE THREAD

**Issue by bhoomikshetty** [AOSSIE-Org/Resonate#194]
Bug: 
"AuthenticationController" not found. You need to call "Get.put(AuthenticationController())" or "Get.lazyPut(()=>AuthenticationController())"

Steps to reproduce the bug: 

1. There should be no rooms available or press the discussion tab and follow the below steps.
2. Press 'Add Icon' button
3. Press 'Pair Chat'
4. Press Cancel.

Fixes (I think can fix this issue):

1. Put AuthenticationController() in TabViewBinding() or make it 'permanent'.
2. Replace 'Get.offAllNamed()' with 'Get.back()' / Get.offUntil().

The first one will fix the issue but won't be able to maintain the state of the previous screen (Landing Screen), which the second fix can.  

@chandansgowda Can you please assign me this issue.

**Comment by Kaps61929** [comment]
@chandansgowda, is this issue still open?
I would love to contribute. Please assign it to me.
