### ISSUE TITLE
Language selection while creating a new room

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#201]
### 🚀 The feature

Currently, we are taking room name, tags and description as inputs while creating a new room. Let's have one more field to specify the language.

**Comment by ShivamMenda** [comment]
@chandansgowda i would like to take this up.

**Comment by SimardeepSingh1450** [comment]
@chandansgowda I would like to take this up, so can you please assign me this issue

**Comment by SimardeepSingh1450** [comment]
@chandansgowda Should i put the languages Array/List from which the user can select inside models folder ?

**Comment by chandansgowda** [comment]
@SimardeepSingh1450 Please look at the pair chat feature where we have a similar implementation

**Comment by SimardeepSingh1450** [comment]
@chandansgowda please review #214 and suggest changes/additions.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
