### ISSUE TITLE
Colliding text entered by the user and lableText on the onboarding screen of the app.

### ISSUE THREAD

**Issue by Jhalakupadhyay** [AOSSIE-Org/Resonate#203]
### 🐛 Describe the bug

whenever there is an empty field left by the user or an invalid name is entered by the user the text from the keyboard and the label text collide giving a very awful UI experience.

https://github.com/AOSSIE-Org/Resonate/assets/89909502/57f1bec3-99e3-4898-a41c-78b00ca00f3c

**Comment by Jhalakupadhyay** [comment]
I have already implemented the solution for it if you can assign me  then i can make changes immediately.


https://github.com/AOSSIE-Org/Resonate/assets/89909502/4b4489da-bb41-42b0-98ea-87235b37d957

**Comment by chandansgowda** [comment]
This should be fixed by now. I guess @ShamanthOP Worked on this.

**Comment by Jhalakupadhyay** [comment]
okk then if not then let me add it

**Comment by ShamanthOP** [comment]
@chandansgowda My bad, I fixed it for just login and signup screen.

**Comment by Jhalakupadhyay** [comment]
> @chandansgowda My bad, I fixed it for just login and signup screen.

Ok sir you will be implementing it or should I add it?

**Comment by ShamanthOP** [comment]
> > @chandansgowda My bad, I fixed it for just login and signup screen.
> 
> Ok so you will be implementing it or should I add it?

Yeah go ahead and fix it...also check other textfields for similar issue

**Comment by Jhalakupadhyay** [comment]
Okk I'll do it

**Comment by chandansgowda** [comment]
Resolved in #206
