### ISSUE TITLE
Feature to Crop image before setting it on the Profile Screen.

### ISSUE THREAD

**Issue by vrundraval24** [AOSSIE-Org/Resonate#207]
### 🚀 The feature

![image](https://github.com/AOSSIE-Org/Resonate/assets/141143426/4610acfc-dcfe-4c09-905e-7ba08993a4af)

WhatsApp and Instagram provide the feature to Adjust or Crop the image before setting it to the profile screen. We can also add something like this in Resonate.

This feature needs to be added to ON BOARDING SCREEN and EDIT PROFILE SCREEN.

### Motivation, pitch

It enhances user experience.

@chandansgowda 
I want to work on this feature. Please assign me.

**Comment by Aditya062003** [comment]
Hi @chandansgowda, I'm keen to contribute to this issue. Is there any way I can assist in resolving it? Thanks!

**Comment by vrundraval24** [comment]
> Hi @chandansgowda, I'm keen to contribute to this issue. Is there any way I can assist in resolving it? Thanks!

Sorry mate, but I am already assigned to this issue. I hope you will find some other issue to work on.

**Comment by chandansgowda** [comment]
Any update @vrundraval24 ?

**Comment by vrundraval24** [comment]
> Any update @vrundraval24 ?

I was working on it... but due to college work and EXAMS... I am not getting enough time... If you want it to be completed ASAP... You can assign the work to someone else, No problem, Sorry for the inconvenience.

**Comment by SharmaDhruv2511** [comment]
Hi, I want to work on this issue if there is no updates from the present assign. If you assign me it would be great. @chandansgowda

**Comment by Aditya062003** [comment]
> Hi, I want to work on this issue if there is no updates from the present assign. If you assign me it would be great. @chandansgowda 

Sorry mate, but I'll complete this soon. Hope you find other good issues to work on.
