### ISSUE TITLE
Check server status before going to home screen

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#211]
### 🚀 The feature

We will have to check if our appwrite server instance is up and running.

**Comment by Jhalakupadhyay** [comment]
can i take this up if available

**Comment by Jhalakupadhyay** [comment]
hello @chandansgowda i have been trying to use the health endpoint for appwrite but it kept showing error the reached to the discord and in support section there is already a support request raised for appwrite's health endpoint and they took it down for sometime ill also raise a support request to know what is the exact staus of the endpoint but till then i think we have to wait or else you have any other way then you can suggest me ill do it.

**Comment by chandansgowda** [comment]
Okay @Jhalakupadhyay . We'll wait until the get back.

**Comment by Jhalakupadhyay** [comment]
@chandansgowda I raised a issue at the Appwrite discord and I got the reply that there is no health endpoint for Flutter we need to find another workaround for verifying the server status, If there are any resources that we can fetch for checking it then it will be easy.

**Comment by Jhalakupadhyay** [comment]
if you have any idea how to proceed further then ill do that.

**Comment by Jhalakupadhyay** [comment]
Hii @chandansgowda did this issue has been resolved ? If not I would like to work on it
