### ISSUE TITLE
Prompt users to upgrade when there is a newer version is available

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#217]
### 🚀 The feature

In order to enhance the user experience and maintain optimal app functionality, we propose the implementation of a version checking and forced app update feature in our project. This feature will enable us to notify users when their current app version is no longer supported, prompting them to update to the latest version.

**Comment by chandansgowda** [comment]
@SimardeepSingh1450 Based on your research, which one would you suggest and why ?

**Comment by Touseef-md** [comment]
Hey, I would like to work on this issue. Could you please assign this to me.

**Comment by SimardeepSingh1450** [comment]
@chandansgowda 
in_app_update : Renders a playstore dialogbox msg for updating.

upgrader, new_version and upgrader : these 3 are almost same and provide a simple dialogbox msg, they provide more of a customisable dialog box.

Making a choice :
If you want users to only use the latest-version: I would suggest to go with in_app_update as it has an inbuilt method to compare the latest version on playstore with current version of user.
But if you want users who are lagging beyond a specific version then I would suggest to go for the other options as mentioned.

**Comment by chandansgowda** [comment]
So since you both ( @SimardeepSingh1450 and @Touseef-md ) I'll be assigning both of you. Please communicate with each other and work on the feature.

**Comment by SimardeepSingh1450** [comment]
@chandansgowda I have made the required changes in pr : #226 , please review the pr and let me know if you want some changes in it .

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
