### ISSUE TITLE
Unconventional user experience - Pressing back button closes the app.

### ISSUE THREAD

**Issue by bhoomikshetty** [AOSSIE-Org/Resonate#222]
### 🚀 The feature

https://github.com/AOSSIE-Org/Resonate/assets/76581406/1d11eaaf-641e-4872-a700-10975e56641e

Users generally intend to get back to the main screen of the apps while pressing the back button. 
In this case, it closes the app, which might be an unconventional user experience. 

### Motivation, pitch

Most of the mobile applications have this kind of behaviour, here is an example

[Youtube](https://github.com/AOSSIE-Org/Resonate/assets/76581406/217b91e7-cf23-476a-b00b-b225fbbb57e1)

**Comment by bhoomikshetty** [comment]
Can you assign me this issue if @chandansgowda you think this is something to worry about

**Comment by r1n1os** [comment]
Is a normal behavior when you are on the main screen of the app and click the back button on the device to take you out of the app. What you can do is to show an alert and ask the user if he wants to quit the app. But I don't think is a good idea.

My opinion is okay the way it works.

One possible solution is to open new screen for that functionality

**Comment by bhoomikshetty** [comment]
That's what, the pair chat screen does not feel like the main screen because we get to the pair chat screen from the main screen. So ideally pressing back button should take the users "back" to the "previous screen".

Moreover, the home page contains the content which will keep users interested and encourage them to stay within the app. Closing the application is like losing user's attention.

**Comment by r1n1os** [comment]
Okay I understand. Can you assign this to me and I will give it a try?

**Comment by bhoomikshetty** [comment]
> Okay I understand. Can you assign this to me and I will give it a try?

I have already started working on this issue.

**Comment by r1n1os** [comment]
Okay. If you need any help fill free to ask 🙂
