### ISSUE TITLE
Validator not added in login Screen

### ISSUE THREAD

**Issue by tarun824** [AOSSIE-Org/Resonate#223]
### 🐛 Describe the bug

We are making an API call for login without checking if the password is empty or not, and the user should know what mistake they are making in login_screen.

solution:
I am adding validator for password TextFormField and checking value is empty or not based on that we will make a API call for login.

**Comment by Touseef-md** [comment]
Hey @chandansgowda, I would like to work on this issue. If tarun is working on this, then it's fine.

**Comment by tarun824** [comment]
Hi @Touseef-md ,I am working in this issue

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
