### ISSUE TITLE
Delete Account Cloud Function

### ISSUE THREAD

**Issue by vrundraval24** [AOSSIE-Org/Resonate#225]
### 🚀 The feature

A feature for deleting a user account. The frontend will be added to the Settings screen. 
And there will be an Appwrite Function which will run on cloud and Delete All User Data. 

There are some things we need to check before Deleting account.
Like Delete all rooms created by user. any scheduled room. Or pair chat. etc...
User email, name, username, dob and at the end The Auth should get deleted.

The front end is already completed.

But Function implementation is remaining.

### Motivation, pitch

I am starting to work on this issue... pls assign it to me @chandansgowda

**Comment by chandansgowda** [comment]
@vrundraval24 Please update this issue description

**Comment by vrundraval24** [comment]
Is the description proper now?

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
