### ISSUE TITLE
Sometimes unable to startup app for development

### ISSUE THREAD

**Issue by SimardeepSingh1450** [AOSSIE-Org/Resonate#227]
### 🐛 Describe the bug

Sometimes when i try to run the app for local development, it gives the below prompt in debug console and shows a black screen on the android device.

![image](https://github.com/AOSSIE-Org/Resonate/assets/92221517/ff8ced56-b50c-427a-8a75-b8a34e757947)

**Comment by chandansgowda** [comment]
This is a know issue but was not showing any black screen before. Do you want to work on it ?

**Comment by SimardeepSingh1450** [comment]
Yes @chandansgowda , let me try to debug this, if i find no solution for the same then will update here.

**Comment by SimardeepSingh1450** [comment]
@chandansgowda I tried to find the problem but was unable to do so, but found that the reason for the problem is somewhere there is an uninitialized variable which is having !. on it due to which this problem is arising , I got this from https://stackoverflow.com/questions/64278595/null-check-operator-used-on-a-null-value , so if someone else can find that one wrongly placed !. it would probably fix the issue.

**Comment by chandansgowda** [comment]
@Aarush-Acharya ??

**Comment by chinmayilondhe** [comment]
Hi @chandansgowda can I try to resolve the issue?

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda I can work on this if it is alright

**Comment by JuanitaCathy** [comment]
I faced the same issue and I tried fixing it. I guess the error could be related to routes as the problem is caused while navigation.
I made some changes in the splash screen file. The black screen doesn't pop up anymore and i can go to other pages but I'm not sure if its entirely fixed :(  
@chinmayilondhe @Aarush-Acharya @SimardeepSingh1450 If its alright and the issue is still open, do i raise a PR on this or would anyone like to test if the fix works for them?

**Comment by SimardeepSingh1450** [comment]
@JuanitaCathy you can try running the same codebase on different devices like on emulator or use external device(having usb debugging enabled) and see if the issue is fixed. :smiley:

**Comment by JuanitaCathy** [comment]
Yup, checked it on 2 external devices and it worked. Just wanted to be extra sure 😅 

> @JuanitaCathy you can try running the same codebase on different devices like on emulator or use external device(having usb debugging enabled) and see if the issue is fixed. 😃

**Comment by SimardeepSingh1450** [comment]
@JuanitaCathy raise a pr and tag @chandansgowda for review
