### ISSUE TITLE
Add GitHub Actions CI Workflow

### ISSUE THREAD

**Issue by JuanitaCathy** [AOSSIE-Org/Resonate#229]
### 🚀 The feature

I'd like to implement GitHub Actions to set up a continuous integration (CI) workflow for this project. This will help automate the build, test, and deployment processes, ensuring a smooth development pipeline.

### Motivation, pitch

This can automate various tasks, such as building, testing, and deploying the application which reduces some work.

**Comment by JuanitaCathy** [comment]
@chandansgowda Can you please assign this issue, I'd like to work on this

**Comment by TheGuyDangerous** [comment]
Seems like a nice issue. Would like to help on this too. @chandansgowda

**Comment by JuanitaCathy** [comment]
@chandansgowda I'm almost done with it, I'll be able to raise a PR as soon as you assign me

**Comment by bhav-khurana** [comment]
@JuanitaCathy
Are you still working on it?

**Comment by JuanitaCathy** [comment]
Yes, I'm still on it

> @JuanitaCathy Are you still working on it?

**Comment by JuanitaCathy** [comment]
There seems to be an error regarding firebase initialization.
@Aarush-Acharya and I are working on resolving, but if @TheGuyDangerous @bhav-khurana would like, 
you can assist us with this :)

**Comment by bhav-khurana** [comment]
Sure, can you provide more details regarding the error?

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
