### ISSUE TITLE
Bug: Text on login page not visible

### ISSUE THREAD

**Issue by bhav-khurana** [AOSSIE-Org/Resonate#230]
## Issue
Some text, e.g., the `Email ID`, `Password` and `New to Resonate` is not clearly visible due to their dark color on the dark background on the application as shown in the screenshot below.

![IMG-20240102-WA0009](https://github.com/AOSSIE-Org/Resonate/assets/96694482/176ac062-e8b3-4e68-8ba5-77dbb6fb3a37)

## Possible Solution
The color of the text can be made lighter so that the user is able to clearly see the text

**Comment by bhav-khurana** [comment]
@jddeep @chandansgowda Can I work on this?

**Comment by puneethkumar18** [comment]
@chandansgowda  i would like work on this issue please assign me

**Comment by MrBooring** [comment]
@bhav-khurana I've raised a PR for this issue also i ve proposed a solution please check Thank you
