### ISSUE TITLE
Adding tests for login/register page

### ISSUE THREAD

**Issue by bhav-khurana** [AOSSIE-Org/Resonate#231]
## Tests
Tests can be added for different screens and functions in the application in order to ensure that the app behaves correctly and whenever a small/big change is to be added, no known bugs are repeated. 

This issue focuses on adding widget/unit tests for the login/register page.

**Comment by bhav-khurana** [comment]
@chandansgowda @jddeep I would like to work on this

**Comment by codesage01** [comment]
can i work on this?

**Comment by siddharthbaleja7** [comment]
@chandansgowda  can you please assign this issue to me

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
