### ISSUE TITLE
Save Changes Visibility Problem in both Light and Dark Mode

### ISSUE THREAD

**Issue by SimardeepSingh1450** [AOSSIE-Org/Resonate#232]
### 🐛 Describe the bug

User cannot clearly see Save Changes text especially in light mode :

<img src="https://github.com/AOSSIE-Org/Resonate/assets/92221517/06efbd0c-5169-4d62-bae2-db02c8e9ae76" width="300" />
<img src="https://github.com/AOSSIE-Org/Resonate/assets/92221517/960808f5-6c0b-4900-b3d1-a4878985445e" width="300"/>

**Comment by SimardeepSingh1450** [comment]
I'd like to work on this issue @chandansgowda , so please assign (will release a pr soon for the same)

**Comment by mahesh-bora** [comment]
Hello @chandansgowda !  I'd like to contribute to this issue, can you pls assign this to me?

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
