### ISSUE TITLE
For adding a search filter for filtering audio rooms

### ISSUE THREAD

**Issue by SimardeepSingh1450** [AOSSIE-Org/Resonate#233]
### 🚀 The feature

I have doodled the red portion where i am suggesting of putting the search filter in the below image .

<img src="https://github.com/AOSSIE-Org/Resonate/assets/92221517/d94b70bb-28f6-4012-97c8-977c293ca6b5" width="300" />

### Motivation, pitch

We should add a search filter (using room name as search parameter) right above audio rooms because later when the application will have lots of rooms it will become difficult for the user to join the room he/she intends to join.

**Comment by SimardeepSingh1450** [comment]
@chandansgowda what do you think of this ? also i think the like and share functionality are also not working (they are just dummy icons) , do you think currently some work can be done on them ?

**Comment by Ivan2001otp** [comment]
@chandansgowda I would like to solve this issue. Kindly provide me the task to me.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
