### ISSUE TITLE
Anonymous Text Size issue

### ISSUE THREAD

**Issue by JuanitaCathy** [AOSSIE-Org/Resonate#235]
### 🐛 Describe the bug

![pairchatissue](https://github.com/AOSSIE-Org/Resonate/assets/114871036/18a4cc8a-8b40-4c52-aa5e-e4ae94e0cf84)

The anonymous text does not fit into the button, so reducing the size should help fix it.

**Comment by JuanitaCathy** [comment]
@chandansgowda I'd like to work on this, please assign.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
