### ISSUE TITLE
Email Verification Pop Up

### ISSUE THREAD

**Issue by JuanitaCathy** [AOSSIE-Org/Resonate#236]
### 🐛 Describe the bug

![emailverissue](https://github.com/AOSSIE-Org/Resonate/assets/114871036/0c985ce7-659d-47be-adf2-b3da4071c9b5)

1. The text "To proceed, verify your email address first." does not fit into the dialog box. Simple sizing fix should solve it.
2. The visibility of verify and cancel texts

**Comment by JuanitaCathy** [comment]
@chandansgowda I'd like to work on this. Also, do you think the size of the dialog box should be increased?

**Comment by bhav-khurana** [comment]
I think the size of the dialog box + the padding should be increased

**Comment by JuanitaCathy** [comment]
> I think the size of the dialog box + the padding should be increased

Yea it's a bit small, thank you!

**Comment by Jhalakupadhyay** [comment]
If the problem is still there can I take up the issue @JuanitaCathy
