### ISSUE TITLE
Testing-friendly dependency injection.

### ISSUE THREAD

**Issue by bhoomikshetty** [AOSSIE-Org/Resonate#237]
### 🚀 The feature

Problem

Usage of Get.find<>() making it difficult to test the application as
proper dependency injection of mock controllers is not possible.

example
e.g.
```dart
class DiscussionsController extends GetxController {
  final Databases databases = AppwriteService.getDatabases();
  AuthStateController authStateController = Get.find<AuthStateController>();
  final CreateRoomController createRoomController = Get.find<CreateRoomController>();
  final TabViewController controller = Get.find<TabViewController>();
  final ThemeController themeController = Get.find<ThemeController>();
  final RoomsController roomsController = Get.find<RoomsController>();
..........
}
```
Solution

Constructor injection, as the mock dependencies can be injected easily.

e.g.
```dart

class DiscussionsController extends GetxController {
  final Databases databases;
  final AuthStateController authStateController;
  final CreateRoomController createRoomController;
  final TabViewController controller;
  final  ThemeController themeController;
  final RoomsController roomsController;

  DiscussionsController({
    required this.authStateController,
    required this.createRoomController,
    required this.controller,
    required this.themeController,
    required this.roomsController,
  });
..........
}
```

```dart
Get.lazyPut(
      () => DiscussionsController(
        authStateController: Get.find<AuthStateController>(),
        controller: Get.find<TabViewController>(),
        createRoomController: Get.find<CreateRoomController>(),
        roomsController: Get.find<RoomsController>(),
        themeController: Get.find<ThemeController>(),
      ),
    );
```

In this case injecting Mock Controller can be injected and tested easily

```dart

Get.lazyPut(
      () => DiscussionsController(
        authStateController: Get.find<MockAuthStateController>(),
        controller: Get.find<MockTabViewController>(),
        createRoomController: Get.find<MockCreateRoomController>(),
        roomsController: Get.find<MockRoomsController>(),
        themeController: Get.find<MockThemeController>(),
      ),
    );
```

### Motivation, pitch

When testing an app, using mock controllers is crucial. It's particularly convenient if dependencies are injected through constructors because it makes it easy to switch between actual and mock controllers. This flexibility enhances adaptability in testing, ensuring smooth transitions for different testing scenarios and improving overall testability and maintainability.

Can I work on this issue @chandansgowda.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
