### ISSUE TITLE
doc: code quality guidelines

### ISSUE THREAD

**Issue by SimardeepSingh1450** [AOSSIE-Org/Resonate#238]
### Issue with current documentation:

There is a need for adding proper coding conventions so as to maintain code structure for easy readability , maintainability and maintaining the code quality. These guidelines can especially be helpful for newcomers to contribute to the project.

**Comment by UtkarshUmre** [comment]
please assign

**Comment by chandansgowda** [comment]
@UtkarshUmre Do you still want to work on this ?

**Comment by charanbhatia** [comment]
@SimardeepSingh1450  please assign this issue to me/

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
