### ISSUE TITLE
Automated to script to setup dev env

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#240]

**Comment by Kaps61929** [comment]
@chandansgowda  can you pls elaborate the issue ?

**Comment by Aarush-Acharya** [comment]
Hey @chandan I would like to take it up

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda  i am almost done will raise a PR asap

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
