### ISSUE TITLE
Implement Forgot Password feature

### ISSUE THREAD

**Issue by JuanitaCathy** [AOSSIE-Org/Resonate#245]
### 🚀 The feature

Implementing the "Forgot Password" feature to provide users with a way to recover their accounts in case they forget or lose their passwords.

### Motivation, pitch

Currently, there is no "Forgot Password" functionality in the application. This feature is a critical component of user authentication as it provides a way for users to regain access to their accounts when they forget their passwords. This feature contributes to the application's usability and user satisfaction.

**Comment by JuanitaCathy** [comment]
@chandansgowda I'd like to work on this if its fine.

**Comment by vijaymehrotra** [comment]
@chandansgowda can i work on this..

**Comment by abhisheksharma010** [comment]
Hello @chandansgowda , can you assign this issue to me? I can easily resolve this.

**Comment by JuanitaCathy** [comment]
I've asked about the access to @chandansgowda and am waiting for his response.

**Comment by chandansgowda** [comment]
Hey @JuanitaCathy You can start working on this feature.

**Comment by Veeransh14** [comment]
Hey, can I work on this issue ?

**Comment by JuanitaCathy** [comment]
> Hey, can I work on this issue ?

I've created a PR on this already
