### ISSUE TITLE
[Feature]: Add GitHub Action Workflow for Greeting Contributors

### ISSUE THREAD

**Issue by harmeetsingh11** [AOSSIE-Org/Resonate#247]
**Description:**
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

### Motivation, pitch

**Proposed Changes:**
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Expected Behavior:**
When contributors create new PRs or issues, the GitHub Action should automatically trigger and post a welcoming message, acknowledging their contributions.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the Contributing Guidelines
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by chandansgowda** [comment]
Hey @harmeetsingh11,
Do you want to work on this issue ?

**Comment by harmeetsingh11** [comment]
@chandansgowda yes!

**Comment by HimaTeju** [comment]
@chandansgowda I believe this issue is still not resolved, I have linked a PR please look into it.
