### ISSUE TITLE
DOC: Need an Installation Guide

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#255]
### Issue with current documentation:
A proper instruction set for installation and getting started is not there for the entire project including the backend part. Leading to confusion for new contributors on running the project and exploring its full functionality

Connecting to the main backend instance requires, the secret credentials (Project Endpoint, Project ID etc) to get compromised. It also utilises the bandwidth storage and request counts of the main backend instance just for the development phase of the project, it would be ideal burn the resources of our true backend instance at the time of V1 and by our apps user base.

It would be great to have a script that automates the initialisation of a dummy Appwrite backend instance that will be a clone of our main backend instance, that the developers could use individually allowing better contributing experience and full control over their own instance, along with it to sync and work with the UI part

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda I would like to work on it please assign it to me

**Comment by charanbhatia** [comment]
@Aarush-Acharya please assign this issue to me
