### ISSUE TITLE
Overflowed error

### ISSUE THREAD

**Issue by abhisheksharma010** [AOSSIE-Org/Resonate#256]
### 🐛 when click on verify email this error is occured

![Screenshot_2024-02-02-18-20-07-87_9cd93bdd924bd20f825d99a76dca2672](https://github.com/AOSSIE-Org/Resonate/assets/108579257/107ec1ae-a401-43e0-8e55-ba3343a230d6)

**Comment by KSURESHCHANDRAREDDY** [comment]
@abhisheksharma010 can i work on this..

**Comment by abhisheksharma010** [comment]
I have completed this waiting for his assigning

**Comment by KSURESHCHANDRAREDDY** [comment]
@abhisheksharma010 I would like to work on it please assign it to me

**Comment by abhisheksharma010** [comment]
I am not the admin of this repository and i am also a contributor and i raise this issue to solve you can work on other issues

**Comment by Aarush-Acharya** [comment]
This is solved
