### ISSUE TITLE
Bug: Appwrite Exception When Unsubscribing from Discussion 

### ISSUE THREAD

**Issue by AyaNady17** [AOSSIE-Org/Resonate#263]
### 🐛 Describe the bug

AppWrite Exception is thrown while trying I'm unsubscribe from discussion. 

![image](https://github.com/AOSSIE-Org/Resonate/assets/144162711/94c7a04b-65ae-44a4-9394-7342375d5099)

I guess this message indicates that the requested route was not found, resulting in a 404 error. This typically happens when the client tries to access a resource (such as an API endpoint) that does not exist on the server.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
