### ISSUE TITLE
[feat] Request for Localization Support

### ISSUE THREAD

**Issue by AyaNady17** [AOSSIE-Org/Resonate#264]
### 🚀 The feature

 I would like to request support for localization (i10n) to make the application accessible to a wider audience. Localization allows users to interact with the software in their preferred language, which is crucial for global adoption.

### Motivation, pitch

-  Users can interact with the application in their native language.
- Global Reach: The project becomes accessible to users worldwide.

**Comment by AyaNady17** [comment]
@chandansgowda @jddeep if you approve this idea, I will start working on it immediately

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
