### ISSUE TITLE
Deprecation Warning: Replace WillPopScope with PopScope

### ISSUE THREAD

**Issue by AyaNady17** [AOSSIE-Org/Resonate#270]
### 🐛 Describe the bug

The Flutter framework has deprecated the usage of WillPopScope constructor in favor of PopScope starting from version v3.12.0-1.0.pre. However, there are still instances of WillPopScope being used in the codebase of the project.

**Comment by theadityaagnihotri** [comment]
I have fixed this issue @AyaNady17 
@jddeep @chandansgowda Please merge the pull request if everything appears to be in order, or alternatively, provide me with feedback.

**Comment by AyaNady17** [comment]
okey, good luck @theadityaagnihotri 👍
