### ISSUE TITLE
The Api Keys and Database Credentials  are clearly visible 

### ISSUE THREAD

**Issue by shuence** [AOSSIE-Org/Resonate#273]
### 🐛 Describe the bug

I navigate through the project today, Pretty easy to setup. 
But when overlooking the project realised that the api keys and database credentials are easily accessible which is kind of risky and potentially the project could be in risk because of it. 

I would be interested if can have .env file which has all the api credentials and if someone really want we can have a drive link of the real api credentials which can be given access when someone requests it.
Also the other way someone can create own firebase and appwrite project and do all the testing in their own environment.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
