### ISSUE TITLE
DOC: Document the code so that newer developers are easily able to understand the code

### ISSUE THREAD

**Issue by bhawesh2002** [AOSSIE-Org/Resonate#275]
### Issue with current documentation:

Newer developers including myself are facing problems in understanding the codebase which makes it difficult to contribute to Resonate.

**Comment by Ivan2001otp** [comment]
Hello @bhawesh2002 please assign this task to me . I can solve this problem.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
