### ISSUE TITLE
Introduce a `develop` branch (GitFlow Workflow)

### ISSUE THREAD

**Issue by mmjsmohit** [AOSSIE-Org/Resonate#28]
This project only has a master branch which will be used for maintaining the releases. I think there is a need for a develop branch so that the main branch is unaffected even if there are some breaking changes in the develop branch.

Refer to this: 
1. [Why need Develop Branch in GitFlow](https://stackoverflow.com/questions/41481858/why-need-develop-branch-in-gitflow)
2. [GitFlow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

Also, let us set up a contributing guidelines file.

**Comment by chandansgowda** [comment]
@mmjsmohit Even I don't have push access. Also, since we are just getting started, as of now, we can work on the main branch itself. Then, once the initial prototype is ready, we can create different branches.

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda, I believe now we have introduced the develop branch hence closing this issue
