### ISSUE TITLE
Subject: Lack of Const Usage Causing Repeated Rebuilds

### ISSUE THREAD

**Issue by kareemabdeen** [AOSSIE-Org/Resonate#280]
### Issue with current documentation:

 Noticed a recurring issue where participants overlook the use of 'const,' resulting in frequent rebuilds. To address this, propose adding the following guideline to the documentation:

Solution: Update the contribution guidelines to include the following lines in the settings.json file of the main project:

"editor.codeActionsOnSave": {
    "source.fixAll": true
}
This configuration will enable Visual Studio Code to automatically handle the 'const' issue each time a contributor saves changes or adds new widgets.

**Comment by kareemabdeen** [comment]
@chandansgowda  , I hope this helps our project to be performed well ❤

**Comment by c-o-d-e-y-o-d-a** [comment]
Hi! I'd like to work on this issue. Can you please assign it to me?

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
