### ISSUE TITLE
Launching results in a 'Null check' error

### ISSUE THREAD

**Issue by mohnishdeshpande** [AOSSIE-Org/Resonate#283]
### 🐛 Describe the bug

I cloned the repo, and faced this issue upon running the app.

![Screenshot_1709170061](https://github.com/AOSSIE-Org/Resonate/assets/77594965/a6fbe706-4332-4933-a85c-c1530954ef09)

Platform: Linux Pop!_OS 22.04 (running Android Emulator)
IDE: VSCode

Flutter doctor output:
![image](https://github.com/AOSSIE-Org/Resonate/assets/77594965/7f499e8f-3076-443b-bc34-deeb1d680f47)

Please let me know if I missed any step or did something wrong.

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
