### ISSUE TITLE
Bug:- Bottom overflowed error on login screen

### ISSUE THREAD

**Issue by bhawesh2002** [AOSSIE-Org/Resonate#287]
### 🐛 Describe the bug

When running resonate on devices of various screen sizes bottom overflowed error is thrown. 
![Screenshot_20240301-102153](https://github.com/AOSSIE-Org/Resonate/assets/55053472/08eb4811-54a5-402f-a2d9-e976c5c4bb91)

**Comment by KuntalGain** [comment]
Hello Sir ,  Can I work on this Issue . I will be capable of fixing this problem

**Comment by Narasimha677** [comment]
Hi @bhawesh2002 , Can I Work on this Issue?

**Comment by puneethkumar18** [comment]
@bhawesh2002  on which device you get error bcz it is working on my device

**Comment by bhawesh2002** [comment]
> @bhawesh2002 on which device you get error bcz it is not showing any error on my device

Moto g40 fusion

**Comment by vrundraval24** [comment]
The issue is solved by PR #324
