### ISSUE TITLE
Image inside circle avatar of Discussion tile , throw an exception NetworkImageLoadException , when user scrolling to this tile 

### ISSUE THREAD

**Issue by kareemabdeen** [AOSSIE-Org/Resonate#300]
### 🐛 Describe the bug

Exception thrown when Iam scrolling to Discussion tile , which have user image inside circle avatar. 
![Screenshot (1638)](https://github.com/AOSSIE-Org/Resonate/assets/118139061/1b5a1833-3580-4716-a58c-e01ad4679b01)

example of the where its throw exception in debug console make user experience bad when scrolling. 
![Screenshot_20240315-135205](https://github.com/AOSSIE-Org/Resonate/assets/118139061/5a1c60ce-bb7a-42d3-86a5-4949f7e83a1b)

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
