### ISSUE TITLE
Bug : Logout button color does not match with app color

### ISSUE THREAD

**Issue by amanraval76593** [AOSSIE-Org/Resonate#315]
### 🐛 Describe the bug

Color of Logout button in profile screen does not match with app color , because of this it fades away in dark mode 

![WhatsApp Image 2024-03-28 at 00 41 49_1accadae](https://github.com/AOSSIE-Org/Resonate/assets/136071018/1f11ec60-70f9-49db-84c1-458665fc8f0a)

**Comment by Aarush-Acharya** [comment]
@kareemabdeen did you take permission from @amanraval76593  before starting work on it as he was the one who opened up the issue

**Comment by Aarush-Acharya** [comment]
hey @kareemabdeen Thank you so much for your contribution, but since you were not assigned we would have to go for @amanraval76593

**Comment by Aarush-Acharya** [comment]
Hey @amanraval76593, @kareemabdeen thank you for the contributions but this issue is already catered to in https://github.com/AOSSIE-Org/Resonate/pull/297
