### ISSUE TITLE
Setup CI/CD for building the app and creating a release.

### ISSUE THREAD

**Issue by ShivamMenda** [AOSSIE-Org/Resonate#319]
### 🚀 The feature

I propose a feature to include CI/CD for the main branch where anytime there's a code push, it builds the package, produces an APK as an artifact, and tags it with a release. 

### Motivation, pitch

This would introduce automation and a release pipeline and it would also help in tagging the releases, it would be a good progress check too, and we can always revert to the last stable build according to the version number in case of any failure.

**Comment by ShivamMenda** [comment]
@chandansgowda @jddeep I can create a workflow for this as it would help the project

**Comment by chandansgowda** [comment]
@ShivamMenda You can start working on this.

**Comment by ShivamMenda** [comment]
Sure @chandansgowda

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
