### ISSUE TITLE
Add New User Registration Flow

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#33]
As of now, there is just a simple signup page asking for email address and the password. We have to add a form to collect basic user details like name, profile pic etc.

**Comment by saiteja13427** [comment]
@chandansgowda Can I work on this?

**Comment by chandansgowda** [comment]
Hey @saiteja13427 
This is already done in a recent open PR.

**Comment by chandansgowda** [comment]
@jddeep This issue has been resolved in #36.
