### ISSUE TITLE
Remove password validation in login screen

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#34]
Form validation had to be added to login and signup forms.

**Comment by saiteja13427** [comment]
@chandansgowda can I work on this?

**Comment by chandansgowda** [comment]
@saiteja13427 You can work on this once the recent PR from Asmit Vimal gets merged.

**Comment by saiteja13427** [comment]
@chandansgowda Sure, will work on it once the PR is merged!

**Comment by chandansgowda** [comment]
Hey @saiteja13427 forma validation is already added. There is a small mistake where we are checking if password meets the standards in login page too. Can you work on removing that ??

**Comment by saiteja13427** [comment]
Sure @chandansgowda, will fix it and get back as soon as possible

**Comment by chandansgowda** [comment]
Any update @saiteja13427 ?

**Comment by chandansgowda** [comment]
I'll work on the issue since there is no update from your side. feel free to chekout other issues to contribute.
