### ISSUE TITLE
You have already registered a tag controller

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#352]
### 🐛 Describe the bug

The bug appears when you go, more than one time to the create new room screen

This is how it shows up in the UI

![Screenshot 2024-10-04 at 4 10 43 PM](https://github.com/user-attachments/assets/a920470c-1618-4ebd-a0f5-d40708b102a2)

**Comment by M4dhav** [comment]
Hey, i can work on this, please assign

**Comment by Aarush-Acharya** [comment]
Sure, follow best practices and let me know once done
