### ISSUE TITLE
Add More Issue types

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#356]
### 🚀 The feature

In need of adding another Issue type 

- Quality Enhancement 

### Motivation, pitch

Not every Issue could be classified in only Bug or Feature or Security Vulnerability

Suggest new different issue types, add once approved

**Comment by Aarush-Acharya** [comment]
When you go to create a new issue github asks you to select a template 
![Screenshot 2024-10-08 at 7 35 34 AM](https://github.com/user-attachments/assets/f25cc70f-1ade-4b6f-bc7b-33144c0550e8)

These are the current 4 options, but we want more template options to be there, one good viable option is Quality Enhancement (meaning enhancing the code base best practices or re-implementation of a current methodology which could add more value to the repository)

So in this sense suggest more options, i believe right now what you stated were issue labels

**Comment by alwaysahustler** [comment]
some new issue types can be--
Help Wanted
Description: Signals that additional help is needed for specific tasks, particularly for contributors looking for smaller pieces of work or assistance with ongoing issues.

 Configuration Change
Description: Involves changes to the project's configuration, such as build tools, CI/CD pipeline adjustments, or environment-specific settings.

Security Improvement
Description: Focuses on identifying potential security risks and requesting improvements to harden the codebase against vulnerabilities.

Can you please assign me @Aarush-Acharya

**Comment by Aarush-Acharya** [comment]
@alwaysahustler  Add the two i listed to your list, create the yaml files and let me know 

Try to be as descriptive and natural as you can

**Comment by Aarush-Acharya** [comment]
Hey I have merged a PR please pull before working further and make sure to work on the dev branch

**Comment by Aarush-Acharya** [comment]
Hey new PR merged please pull before moving forward

**Comment by Aarush-Acharya** [comment]
yes it is, awaiting updates from @alwaysahustler

**Comment by vanshambansal** [comment]
hey is the issue open?

**Comment by Aarush-Acharya** [comment]
hey @vanshambansal this issue is open @alwaysahustler any updates on this ??

**Comment by vanshambansal** [comment]
@Aarush-Acharya i would start my work on it asap
