### ISSUE TITLE
Picture Image resolution too high

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#358]
### 🐛 Describe the bug

The picture being used as an emoji for no connection dialog and no room dialog is of 1800 x 1800 resolution which is very high. The resolution makes the current size of the Images to be around 4 mb each which is too much 

Scale the images down to 10Kb. If the image resolution falls below acceptance once you reach this image size then just simply replace it with a Text Emoji but the size should be around 10Kb

**Comment by M4dhav** [comment]
I can work on this, just downscaling of the image is required right

**Comment by xkaper001** [comment]
Hi @Aarush-Acharya ,

I noticed that this issue is unassigned, and I'd love to work on it! I'm familiar with the technology used in this project and I believe I can help resolve it.

Could you please assign this issue to me?

Thank you!

**Comment by Aarush-Acharya** [comment]
hey @xkaper001 I am assigning the issue to you. Make sure you take care of the trade off (i.e reduce while quality still remains acceptable)

**Comment by xkaper001** [comment]
> hey @xkaper001 I am assigning the issue to you. Make sure you take care of the trade off (i.e reduce while quality still remains acceptable)

Sure :)

**Comment by Aarush-Acharya** [comment]
Hey I have merged a PR please pull before working further and make sure to work on the dev branch

**Comment by Aarush-Acharya** [comment]
Hey new PR merged please pull before moving forward

**Comment by maiHydrogen** [comment]
Hi @Aarush-Acharya 
I am new to this opensource thing but I am quite familiar with the flutter + firebase things as i saw this issue labelled as good first issue i thought i should give it a try too.
can i work on it?

**Comment by Aarush-Acharya** [comment]
hey @maiHydrogen, @xkaper001 is already working on it, 

hey @xkaper001, any progress update ?

**Comment by xkaper001** [comment]
hi @Aarush-Acharya, Yes I've almost completed the work to fix this issue. Will send a PR latest by tomorrow.

**Comment by Aarush-Acharya** [comment]
hey @xkaper001, got it

**Comment by xkaper001** [comment]
hey @Aarush-Acharya, I face the following
1. When I compress the image down to 10kb, The image becomes pixelated something like this, 

![dizzy-face-10kb](https://github.com/user-attachments/assets/777a5b61-7f3a-4833-b6cd-20a2ad9447e6) ![no_rooms_10kb](https://github.com/user-attachments/assets/8e560f4a-7b8b-49ac-9bbf-02bb5ed2de0b)
which worsens the user experience. 

2. Compressing it to somewhere around 25 and 29kb seems fine to me, like

![no_connection_24](https://github.com/user-attachments/assets/678456ce-5ce0-4348-8c1e-ee602c25fc83) ![no_rooms_29](https://github.com/user-attachments/assets/9482908b-eb50-4a77-b7e0-41a38e26e846)

3. Also the text emoji alternative doesn't work, it also is blur at that level
![screenshot](https://github.com/user-attachments/assets/a2a315e9-e116-4769-bca7-8d5af037a9db)

What are your views? Which path should I go? I propose to use 2nd method where compressing it to less than 30 kb seems fine to me.

**Comment by Aarush-Acharya** [comment]
Hey @xkaper001, second method feels fine, though our initial target was to keep them below 10kb 

I feel it should be fine but do research a little more on it and let me know what better could be done for now let's go with the 30 on but please do look into it more 

There isn't a hard requirement to use the emojis only we can go with illustrations as well but then we would have to update the colour of the illustration according to the primary colour of the theme 

Could you research more on this next ? It is possible to do that

**Comment by xkaper001** [comment]
Hey @Aarush-Acharya, I found out a way to compress images down to 10kb to fit our needs :) Also I choose to stick to these two emojis coz they're elegant imo, and fits well with our simplistic UI. 

> All the below emoji's are less than 10KB

Here are the images
![h2](https://github.com/user-attachments/assets/ca71a1fb-3732-43f7-9c78-fc08f4ff92ab) ![h](https://github.com/user-attachments/assets/14d2844d-ca6f-46cd-b73d-6907b02c7552)
 
Also I propose to change this emoji png with a new one, reason: The pensive face emoji looks kinda depressed/a little too sad imo (totaly my opinion). I'll go with what you say.
![sad](https://github.com/user-attachments/assets/785c92c3-ea5c-4a0f-b044-8672aa68e331)  to ![h](https://github.com/user-attachments/assets/14d2844d-ca6f-46cd-b73d-6907b02c7552)

## Final Screenshots/ Output

![image](https://github.com/user-attachments/assets/6e3bbf52-4bf8-491d-8b04-10fbccd1144a) ![image](https://github.com/user-attachments/assets/161da938-463f-4746-ac6a-0c4d03b6152c)

**Comment by Aarush-Acharya** [comment]
hey @xkaper001, sincere apologies for my late response

Yep this looks good please make the PR will review and get to merging it

**Comment by xkaper001** [comment]
hmm sounds interesting.. I'll research on that and get back to you. for now I'll just create an issue.
