### ISSUE TITLE
URGENT: Updation of dependencies required for running the app.

### ISSUE THREAD

**Issue by xkaper001** [AOSSIE-Org/Resonate#360]
# Description
I was assigned #358. To start working on it, I cloned the repo. But while running the app, I got a lot of errors (attached below). I observed the codebase thoroughly and found that the dependencies  in `pubspec.yaml` file are outdated. For reference, the version used for appwrite is `v9.0.1` while the latest version is `v13.0.0`. I propose the updation of the dependencies and related code in the codebase to also comply with the latest flutter versions.

# Steps to produce
1. Setup Flutter Development environment with latest flutter version `v3.24.3`.
2. Clone the repo.
3. Run `flutter pub get`.
4. Run `flutter run`.
5. Observer errors. 

# Errors
```debug
Launching lib/main.dart on CPH2467 in debug mode...
../../../../.pub-cache/hosted/pub.dev/win32-5.2.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/win32-5.2.0/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/win32-5.2.0/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(guid));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/win32-5.2.0/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
  factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/win32-5.2.0/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/denji/dev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

```

# `flutter doctor` output
```bash 
$ Resonate git:(xkaper001/issue358) ✗ flutter doctor                      
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on Nobara Linux 40 (GNOME Edition) 6.11.1-206.fsync.fc40.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.94.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
``` 

# Proposed Solution
I propose the updation of the dependencies and related code in the codebase to also comply with the latest flutter versions.

![image](https://github.com/user-attachments/assets/4de930ce-9ad5-4c6d-8215-2533bbf42525)

**Comment by xkaper001** [comment]
Hi @Aarush-Acharya ,

I raised this issue and I'm confident I can resolve this issue which will also give way for other contributors to contribute to **Resonate**. Could you please assign this issue to me?

Thank you!

**Comment by Aarush-Acharya** [comment]
@xkaper001  which branch are you talking about here? 

Work on the dev branch

**Comment by Aarush-Acharya** [comment]
Hey I have merged a PR please pull before working further and make sure to work on the dev branch

**Comment by xkaper001** [comment]
> @xkaper001  which branch are you talking about here? 
> 
> Work on the dev branch 

oops sorry my bad :')
