### ISSUE TITLE
Animated Splash Screen Redirects context to null

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#370]
### 🐛 Describe the bug

The animated containers used in the splash screen redirect the context and change route to null and this causes a blank screen to appear

This happens randomly sometimes happens sometimes does not, but the problem is the bad use of animated containers on the splash screen

Thus, splash screen needs a little redesigning

What the error looks like 
![Screenshot 2024-10-12 at 10 52 52 AM](https://github.com/user-attachments/assets/f1b91b70-1aaa-4966-bcac-71d72f3d467e)

**Comment by ParadoxNJ005** [comment]
Sir, I would like to work on this issue

**Comment by Aarush-Acharya** [comment]
Hey @ParadoxNJ005, i am assigning this issue to you please make sure to follow best practices and get it done timely 

thank you

**Comment by ParadoxNJ005** [comment]
Sir , While exploring the code, I found that the splash screen wasn't correctly implemented. I resolved the issue, and now the app smoothly displays the splash screen before going to the landing page. Let me know if there's anything else that needs attention!
![pic](https://github.com/user-attachments/assets/d097414d-ba18-4ab1-89d1-cb5bcdab74a8)

**Comment by Aarush-Acharya** [comment]
Hey @ParadoxNJ005, nothing as of now 

But we are open to suggestions if you feel it could offer some addition of value to the project.

Please make PR of your current changes so that i could review and test your changes 

Thanks a lot for the contribution

**Comment by Aarush-Acharya** [comment]
Hey @ParadoxNJ005, any update on so ??

**Comment by Aarush-Acharya** [comment]
this issue has been resolved
