### ISSUE TITLE
UserName Not Available Indication

### ISSUE THREAD

**Issue by puneethkumar18** [AOSSIE-Org/Resonate#387]
### 🚀 The feature

when user enter the  Username it only show green icon if it is available 
we could also display the not available message

### Motivation, pitch

It will guide user to get. the available username

**Comment by puneethkumar18** [comment]
hey I would like work on this issue @Aarush-Acharya could pls assign this issue to me

**Comment by SachinSaiTej** [comment]
@chandansgowda @Aarush-Acharya
I would like to work on this.

**Comment by Aarush-Acharya** [comment]
hey @puneethkumar18, this looks good please start work on it assigning it to you

Hey @SachinSaiTej please do look for more areas to contribute looking forward to contributions from your side
