### ISSUE TITLE
Url Incorrect which is giving Error

### ISSUE THREAD

**Issue by puneethkumar18** [AOSSIE-Org/Resonate#388]
### 🐛 Describe the bug

![Screenshot_1730354995](https://github.com/user-attachments/assets/61590c11-3a9a-492e-a067-e6ad002b290b)
While creating a new story Not able To fetch the Image and also in Create chapter as well

**Comment by Aarush-Acharya** [comment]
hey @puneethkumar18, are you running it on a physical device or an emulator?

**Comment by puneethkumar18** [comment]
> hey @puneethkumar18, are you running it on a physical device or an emulator?
 
I am running on Emulator

**Comment by Aarush-Acharya** [comment]
> > hey @puneethkumar18, are you running it on a physical device or an emulator?
> 
> I am running on Emulator

You need to run the new backend script so that the script handles the plugin of the default images for stories and chapters into your local appwrite instance 

Please follow the recently updated onboarding guide to get a walk through the backend env set up

**Comment by puneethkumar18** [comment]
@Aarush-Acharya  i have setup according to your latest onboarding guide there and Error is in the url there mentioned name of that image instead of id if it is correct that Error Would be get Resolved

**Comment by Aarush-Acharya** [comment]
hey @puneethkumar18, it was pointing to file ID only but in the recent update to the script in backend the ID got changed, you are correct please do put in the correct Id of it, and also if you can try to implement default profile image url based on the theme

**Comment by puneethkumar18** [comment]
Okay @Aarush-Acharya I understood your suggestion I would like to work on this please assign this task to me so I can work on this 


Thank you for your suggestion I had a different view it got cleared

**Comment by puneethkumar18** [comment]
I have raised the PR @Aarush-Acharya  please check if in case any changes need suggest me
