### ISSUE TITLE
Implement Dynamic Theming for SVG Illustrations - Primary Color Adaptation

### ISSUE THREAD

**Issue by xkaper001** [AOSSIE-Org/Resonate#397]
### 🚀 The feature

Enable SVG illustrations within the app to adapt their primary color dynamically based on the theme, enhancing the app's visual coherence and user experience.

### Motivation, pitch

Currently, the SVG illustrations in the app have a static primary color, which may not always align with the active theme, especially if users switch between light and dark modes or customized themes. This feature would elevate the app’s aesthetic by allowing SVGs to seamlessly integrate with any chosen theme, improving consistency across UI elements.

**Comment by xkaper001** [comment]
Hi @Aarush-Acharya ,

I’ve created this issue to address dynamic color adjustments for SVG illustrations based on the theme. I'd like to request an assignment for this, so I can start working on a solution. Please let me know if there’s any additional guidance or specific requirements.

Thank you!

**Comment by xkaper001** [comment]
Here is a demo of what I plan/propose

# 1. Change of No Connection Illustration

<img width="35%" src="https://github.com/user-attachments/assets/6e3bbf52-4bf8-491d-8b04-10fbccd1144a">
<img width="35%" src="https://github.com/user-attachments/assets/6e3bbf52-4bf8-491d-8b04-10fbccd1144a">
![image](https://github.com/user-attachments/assets/ab774870-0735-4196-abf8-675941af6993)

**Comment by xkaper001** [comment]
Here is a demo of what I propose/ plan to improve

# 1. No Connection Illustration Instance

## Current
<img width="35%" src="https://github.com/user-attachments/assets/b362c403-4c6e-474c-95c6-20b99bc120fe"> 

## New/Proposed
- Dynamic Coloring Based on current theme's primary color.
 
<img width="35%" src="https://github.com/user-attachments/assets/02180ec5-6be7-4c30-a66b-f965f417a5ae"> <img width="35%" src="https://github.com/user-attachments/assets/3c580227-1865-4376-8023-45f9f2f20080"> <img width="35%" src="https://github.com/user-attachments/assets/1d547e06-36bb-44d9-b44b-b28f224202ce"> <img width="35%" src="https://github.com/user-attachments/assets/ef07798d-0213-4357-bd3b-8557cadd8ebc"> 

# 2. No Room Illustration Instance

## Current
<img width="35%" src="https://github.com/user-attachments/assets/fc56e39c-29b4-4227-870d-bd486984cea7"> 

## New/Proposed
- Dynamic Coloring Based on current theme's primary color.

<img width="35%" src="https://github.com/user-attachments/assets/e4c69487-834b-4311-90b5-25f93dbc5493"> <img width="35%" src="https://github.com/user-attachments/assets/fcf959fc-fef1-4705-96b6-dad918ee50f0"> <img width="35%" src="https://github.com/user-attachments/assets/028a3ec1-250d-4927-9a09-0789706a2c75"> <img width="35%" src="https://github.com/user-attachments/assets/7b36a515-ac06-494e-9b5d-c853d2478e82"> 

### Alternate Illustration for No Rooms
<img width="35%" src="https://github.com/user-attachments/assets/8a468ccb-bad2-4853-ab9f-b1505575870e">

**Comment by Aarush-Acharya** [comment]
Hey @xkaper001, I think that the new designs look great 

But please explain the your approach of implementation that you have in your mind for it

**Comment by xkaper001** [comment]
Okay, So I started researching for ways to dynamically change the theme of SVG images, and found out that either of the following two ways could be used:
1. Editing SVG Image Code internally to change colors based on colors provided.
2. Using `flutter_svg`'s ColorFilter/ BlendMode to blend the svg based on a particular color(from the theme).  

Using the option 1, one could manipulate complex multi-color SVG images, But It has a more complex approach and also would unnecessarily complicate our codebase over such a minor feature. In my opinion, going with the option 2 was a wiser approach. Tho only condition was that only single colored simple svg could be used to 

After researching and browsing the web (a lot) I found two open souce/royalty free SVG images to use in our app. 

## Approach of Implementation

Using `flutter_svg` package's `ColorFilter` with `BlendMode` as `modulate`  to blend the svg with the app theme color.

```dart
SvgPicture.asset(
  AppImages.noConnectionSvg,
  height: 200,
  width: 200,
  colorFilter: ColorFilter.mode(
    Theme.of(context).colorScheme.primary,
    BlendMode.modulate,
  ),
),
```

**Comment by Aarush-Acharya** [comment]
Hey @xkaper001, looks great good work

Raise a PR once done with the implementation of `flutter_svg` method i.e second option and testing with every theme the 

- No connection illustration
- No room illustration 

for no room illustrations please choose the Alternate Illustration for No Rooms

**Comment by Aarush-Acharya** [comment]
Hey @xkaper001 got it my bad
