### ISSUE TITLE
Get user data if not available on firestore

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#45]
There's a scenario wherein 
1. The user registers a new account
2. When the onboarding screen appears, user closes the app and reopens it
3. Now, there is inconsistency in user data on firestore (i.e user has not filled onboarding form)

This has to be fixed.

**Comment by beSaif** [comment]
Can I work on this?

**Comment by puneethkumar18** [comment]
Can you explain bit more

**Comment by chandansgowda** [comment]
@puneethkumar18 Please follow the steps I have described in the issue while running the app on a device. If you still have doubts, let me know.

**Comment by chandansgowda** [comment]
@beSaif You can work on the issue and send in a PR

**Comment by chandansgowda** [comment]
Any update @beSaif @puneethkumar18  ?

**Comment by chandansgowda** [comment]
Its okayy @beSaif 
I'm working on this.

**Comment by puneethkumar18** [comment]
..
