### ISSUE TITLE
UI: Implement App Screens

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#47]
This issue tracks the implementation of UI designs/views. We can work on improving the UI and add elements as and when required. For now, the following screens/widgets have to be implemented. Feel free to make improvements to the proposed design.

- [x] SignIn/SignUp Screen
- [x] User Onboarding Screen
- [x] Rooms List Screen
- [x] Single Room Screen
- [x] Create Room Popup
- [x] Profile Screen

SignIn Screen            |  Signup Screen | User Onboarding           
:-------------------------:|:-------------------------:|:-------------------------:
![login](https://github.com/AOSSIE-Org/Resonate/assets/41890434/10610ef3-5475-4c46-85a2-8034530b1f70)  |  ![signup_screen](https://github.com/AOSSIE-Org/Resonate/assets/41890434/9409391c-1f3a-478f-bb79-b9b70de94037) | ![onboard](https://github.com/AOSSIE-Org/Resonate/assets/41890434/37063293-882b-42ae-b344-1373b19b6f2a)

Rooms Screen | Create Room Popup            |  Single Room Screen
:-------------------------:|:-------------------------:|:-------------------------:
![rooms_screen](https://user-images.githubusercontent.com/41890434/229134926-313fae1b-2f5d-4d19-b036-2082cf24f347.png) | ![create_room](https://user-images.githubusercontent.com/41890434/229134951-d7b6d77b-8a6d-4fc7-8fd9-99bba6b56bc3.png)  |  ![room_screen](https://user-images.githubusercontent.com/41890434/229136723-02c56d8d-137b-466b-9743-5027ab062fd6.png)

**Comment by chandansgowda** [comment]
I'm working on the home screen (Room List Screen as of now). The other screens are still open for contributions.

**Comment by Aarush-Acharya** [comment]
I would like to take up the create room pop up screen if it is open for contribution

**Comment by chandansgowda** [comment]
@Aarush-Acharya This issue open only for gsoc contributors. Feel free to checkout bugs and improvement issues. You can also test the app and raise issues.

**Comment by Aarush-Acharya** [comment]
Okay thnks

**Comment by Aarush-Acharya** [comment]
understood
