### ISSUE TITLE
A Null image as Profile is shown if the user does not provide an Image 

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#54]
I am currently working on this issue setting the placeholder image as the profile picture of the user incase of no image provided by user can also implement to set different placeholders specific to Gender if required..

**Comment by chandansgowda** [comment]
@Aarush-Acharya I think this was already worked upon in #39

**Comment by Aarush-Acharya** [comment]
Well it is there for onboarding screen but it is not showing up in profile screen if the user has not provided a picture in onboarding

**Comment by chandansgowda** [comment]
Okay. Let me know if you need any help.

**Comment by Aarush-Acharya** [comment]
Thanks

**Comment by chandansgowda** [comment]
Hey @chandansgowda 
Thanks for the contribution. We have planned of replacing firebase with appwrite and hence the PR which fixes this issue cannot be merged until the migration to appwrite takes place. You can still work on improvements or bugs not related to the backend.

**Comment by Aarush-Acharya** [comment]
Hello @chandansgowda  
Thank you for the information, 

But this PR also contains a fix for a UI-related issue so shall I create a different PR for it ?

And again if we are to navigate to I would also like to assist in it or if it is alright can I take it up

**Comment by chandansgowda** [comment]
@Aarush-Acharya It's so encouraging to see your interest in the project, but this issue will be worked upon by me under GSOC. We will be using appwrite for authentication also. Have an eye on the project issues and work on those which are not labelled gsoc. Feel free to suggest improvements or report bugs and work on them.

**Comment by Aarush-Acharya** [comment]
this was closed while migrating to Appwrite
