### ISSUE TITLE
Suggestion: Loading Animation for Resonate 

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#58]
A loading animation for Resonate replacing the default flutter loading animation (splash screen  which provides a loading animation when Resonate starts currently a default flutter loading animation is being shown would customize it for Resonate )

Would like to work on it

**Comment by chandansgowda** [comment]
Hey @Aarush-Acharya 
You can now work on the issue. Let me know if you need any help.

**Comment by Aarush-Acharya** [comment]
Thanks
