### ISSUE TITLE
Suggestion: Need of Delete Account Button in Profile Screen 

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#59]
While debugging I had to create a lot of dummy accounts this led to a need of including a delete account Button in the profile screen allowing others to delete their account if required hence allowing other users to be able to use the username they were previously holding 

Would like to work on it

**Comment by Aarush-Acharya** [comment]
Hello @chandansgowda 
I had a doubt as we are to migrate to appwrite so the work on this issue would also be paused until the migration is complete.

**Comment by chandansgowda** [comment]
Yes. You can just work on the UI part till then.

**Comment by Aarush-Acharya** [comment]
This issue is a subset of #93 please refer it

**Comment by Aarush-Acharya** [comment]
This issue is a subset of https://github.com/AOSSIE-Org/Resonate/issues/93 please refer it
