### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#61]
Currently when the app restarts, we get to see the login screen for a second or so even if we are logged in. This leads to bad user experience. A better approach is to have a splash screen until the authentication controller checks if the user is already logged in and then navigate accordingly.

**Comment by Aarush-Acharya** [comment]
hey @chandansgowda  
I would like to take this up as this I believe is an extension of the loading screen issue which is responsible of showing a splash screen resonate starts

**Comment by chandansgowda** [comment]
@Aarush-Acharya You can take this up.

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda 
Apologies for the delay I have built two splash screens one is a native splash screen using [flutter native splash](https://pub.dev/packages/flutter_native_splash) the other is a custom (not native) implemented with the help of [animated splash screen](https://pub.dev/packages/animated_splash_screen) plugin which loads and would always load after the native one. The default native is a white screen with a Flutter logo which is customized using the Flutter native splash plugin.

Please do let me know which one to keep the first being the native and the second the custom

Native perks and drawbacks:
perks: Loads the app faster looks smooth
drawback: Does not support customization of higher degrees like transition animations etc. Poses limitations on UI like splash icon size and format for specifically Android 12 (the splash icon would be clipped in a circle in the center of diameter 768 pixels hence should be sized accordingly).

Customs perks and drawbacks:
perks: It is basically a screen we design just like login, signup, and onBoarding screens hence more flexible and supports transition animations enhancing UI

drawbacks: can only load after the native splash screen, if to select this the native is provided with the same background and a proxy_image is just the plain canvas with background color hence nullifying the UI effect of the native screen. Thus the native screen loads but it is just the background and does take a second to load hence making it seem like the custom splash screen loads after a second

I would prefer to go with the second as it enhances the UI and not mind letting the app taking an extra second to load and also the logic for preventing the login screen to show up has been written for this case

https://github.com/AOSSIE-Org/Resonate/assets/92685647/37d8bfdc-3661-4a24-83f0-7074d12761dc

Do let me know which to proceed with

**Comment by chandansgowda** [comment]
Let's go with the second one. Make changes above ui-room branch in my fork.

**Comment by Aarush-Acharya** [comment]
Understood, so am I to make the PR on your fork or onto ResonateOrg?

**Comment by chandansgowda** [comment]
You can fork my fork and then create a branch on top of ui-theme and work on it. Once my PR gets merged, you can raise a PR directly to AOSSIE's repo

**Comment by Aarush-Acharya** [comment]
understood, will add new branch with uitheme branch as base after forking your fork, would add the splash screen in that branch and then create a PR to your fork

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda 
I am unable to fork as one fork already exists of the main org repo I have directly cloned your fork created a new branch and will push the branch after the work is done would this be alright

**Comment by Aarush-Acharya** [comment]
I am facing a denied access issue even with a new branch would you be fine with providing the access or shall I delete my current fork and fork your fork

**Comment by chandansgowda** [comment]
Fork my fork and check.

**Comment by Aarush-Acharya** [comment]
okay understood
