### ISSUE TITLE
Need for Logo Icon for Resonate 

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#65]
An app logo icon I believe is needed for Resonate along with its design needs to be finalized I believe it would differ from the AOISSIE-Org logo.

<img width="131" alt="Screenshot 2023-06-21 at 9 49 06 AM" src="https://github.com/AOSSIE-Org/Resonate/assets/92685647/6450043f-bd7e-4738-ad52-bb21152c0821">

Currently being the default flutter logo, after finalizing the logo the splash screen I believe might also have to be updated the finalized logo being at the center with the organizations logo being at bottom center

**Comment by Aarush-Acharya** [comment]
would like to take this up along with the design of it, give me a days time would try to update shortly

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda 

<img width="680" alt="Screenshot 2023-06-21 at 3 18 12 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/92685647/52c49d58-2f95-48bb-ba68-0bc5ee681be9">

These are the logos that I found and edited please do let me know

**Comment by chandansgowda** [comment]
These look great. Can we modify them in any way to show what Resonate is about?

**Comment by Aarush-Acharya** [comment]
Yes for that purpose I guess B and C lie very close so please choose one of them would modify the chosen one in order to achieve a better appeal

**Comment by chandansgowda** [comment]
Great job @Aarush-Acharya 
We can go ahead with this logo. Before that see if you can make it a bit more minimalistic.

**Comment by Aarush-Acharya** [comment]
which one first one or the second

**Comment by Aarush-Acharya** [comment]
Thank you so much @chandansgowda 

I have updated the first one please do take a look and let me know which one of the two is to be worked on for attaining minimalism

**Comment by chandansgowda** [comment]
B looks better. See if you can remove those two person icons.

**Comment by Aarush-Acharya** [comment]
Understood thanks

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda 
thanks for the suggestion 
This is what it looks like without the person icons 

<img width="375" alt="Screenshot 2023-06-21 at 10 38 15 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/92685647/ed2c3325-920c-4aff-956c-1acb33f26f57">

Do let me know of any changed required

**Comment by chandansgowda** [comment]
check the one you mentioned as B

**Comment by Aarush-Acharya** [comment]
Oh sincere apologies 

<img width="425" alt="Screenshot 2023-06-21 at 11 12 04 PM" src="https://github.com/AOSSIE-Org/Resonate/assets/92685647/86444fb3-b8f8-44e9-a74d-1c14ae046c4b">

this is what the B looks like after removing the 2 person icons

**Comment by chandansgowda** [comment]
This looks good. We can go with this for now @Aarush-Acharya. Please change the icons ok both android and ios projects and raise a PR.

**Comment by Aarush-Acharya** [comment]
Okay understood  @chandansgowda  on it,

After the merge of it shall I redesign the splash screen with this logo popping before AOSSIE's hence making it two screens

The second option is to create a single screen with this new logo at the center and AOSSIE's at the bottom center as the brand logo.

or is the current splash screen doing perfectly well

**Comment by chandansgowda** [comment]
Lets go with the second option.

**Comment by Aarush-Acharya** [comment]
Understood will implement it with custom
