### ISSUE TITLE
docs: add appwrite setup instructions

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#70]
Add instructions to setup Appwrite according to our project. Update the readme file.

**Comment by abhishek09827** [comment]
Hello @chandansgowda pls assign this task to me

**Comment by chandansgowda** [comment]
@abhishek09827 Please go ahead.

**Comment by Yougesh978** [comment]
If you could elaborate the problem statement a bit more, I would like to complete this issue.

**Comment by hritvik715** [comment]
claim

**Comment by Aarush-Acharya** [comment]
Hey thank you so much, for your sincere contributions to the project. Unfortunately though as we are moving towards a whole new revised version of Resonate. We would have to start fresh with the issues as in the new version of UI and some new features under development a lot has changes. Once the new version is out we will start accepting issues again and sprint through them including implementing merging pushing Resonate to even newer heights
