### ISSUE TITLE
Implement LiveKit Room Service

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#72]
Create a controller to manage LiveKit room using the methods provided by the LiveKit Client SDK for Flutter.

**Comment by akshaymagar2003** [comment]
can you please assign this task to me

**Comment by chandansgowda** [comment]
@akshaymagar2003 Issues labelled GSoC are only for gsoc contributors. Fee free to check other issues or raise enhancement or bug fix issues.

**Comment by akshaymagar2003** [comment]
ok thank you
