### ISSUE TITLE
Email Verification Screen Needed 

### ISSUE THREAD

**Issue by Aarush-Acharya** [AOSSIE-Org/Resonate#75]
An Email verfication screen and logic  needed while sign up to avoid users to enter false emails and to ensure the email entered belongs to them would implement OTP format to validate emails

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda please do assign this to me if possible

**Comment by chandansgowda** [comment]
@Aarush-Acharya How are you planning to verify emails?

**Comment by Aarush-Acharya** [comment]
Using this package
 https://pub.dev/packages/email_otp
 Or 
 https://pub.dev/packages/email_auth
 Or
 Can build a custom designed Python server to do so 
 
Would like to go with first or third as having a few doubts in seconds documentation

**Comment by chandansgowda** [comment]
@Aarush-Acharya Appwrite has methods to verify emails. Please check that.

**Comment by Aarush-Acharya** [comment]
Okay thank you looking into it

**Comment by Aarush-Acharya** [comment]
Hey, @chandansgowda  I looked into it well it serves a different functionality than what I imagined as it only works after a user has logged in to Appwrite similar to user verification systems. I had a different approach in mind like the user cannot sign in if the email isn't verified only after verification of the email can the account be created

https://appwrite.io/docs/client/account?sdk=flutter-default#accountGetPrefs:~:text=Here%20to%20Copy-,Create%20Email%20Verification,-POST

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda creating two functions on Appwrite one for OTP send and the other for OTP verification both would write to a new Appwrite database, first writing the OTP  along with OTP ID (ID would be sent as a response to Flutter) while the second would receive the OTP ID along with Verification ID (generated at Flutter) as initial data from Flutter and would write the Verification ID along with Verification Status to the database. As the verification ID was generated at the Flutter no need to send it as a response from function 2

Do let me know if this approach is alright also would be using [flutter_otp_text_field](https://pub.dev/packages/flutter_otp_text_field) plugin for OTP text field

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda two of the functions have been implemented please do test them 
Format must be follow point to point just the values inside inverted comas can be changed
Send OTP Function

`{
"email": "example@gmail.com",
"otpID": "sample_otp_Id"
}`

Verify OTP Function 

`{
"otpID": "sample_otp_Id",
"userOTP": "<Generated OTP sent to your mail>",
"verify_ID": "sample_id"
}`

_**The "otpID" must be the same for the both for one cycle**_

The call would be made in a similar fashion from the frontend
