### ISSUE TITLE
App crashes on launch if there is no internet connection

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#80]

**Comment by Aarush-Acharya** [comment]
@chandansgowda shall I look into it

**Comment by Aarush-Acharya** [comment]
I would like to take this up

**Comment by chandansgowda** [comment]
This only checks if the device is connected to wifi, mobile dat etc.. Or will it check for internet connection also ??

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda  apologies for the late response could please elaborate on what you mean by internet connection is it like the user is connected to mobile data or wifi but his plan isn't paid  so he isn't connected to the internet 

Also I believe it does check for internet connectivity also https://www.flutterbeads.com/flutter-internet-connection-checker/#:~:text=To%20check%20the%20internet%20connection%20in,method.
