### ISSUE TITLE
Show placeholder if there are no active rooms

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#88]

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda would like to take this up

**Comment by chandansgowda** [comment]
That is a sample room. But now what we need is, if there are zero active rooms, we should show an illustration saying no active rooms and also we should have a button to reload the page.

**Comment by Aarush-Acharya** [comment]
Alright understood would do so

**Comment by Aarush-Acharya** [comment]
Alright understood would do so

**Comment by ShivamMenda** [comment]
Hey, @chandansgowda If this issue is still open can I take it up?

**Comment by chandansgowda** [comment]
@Aarush-Acharya Since this is a good-first-issue, I'll be assigning this to @ShivamMenda

**Comment by ShivamMenda** [comment]
Thank you @chandansgowda, I will use the visibility Widget to work on this. If the list that contains the room is empty will show the No room widget else will show the list of rooms.
