### ISSUE TITLE
Feature for admins to assign moderators for the room

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#91]

**Comment by AKASHANGADII** [comment]
Hey @chandansgowda can you assign me this issue

**Comment by chandansgowda** [comment]
Hey @AKASHANGADII 
This issue requires an understanding of the whole project. Are you sure you can take this up?

**Comment by AKASHANGADII** [comment]
Okay.
I'll try this later

**Comment by ShamanthOP** [comment]
@chandansgowda I would like to work on this
