### ISSUE TITLE
Duplicate participant records in database

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#96]
To reproduce this issue:
1. Create a Room 
2. Hot restart the app
3. Join the room you had created earlier
4. You will get multiple participant blocks 

Ideally, there should be only one admin block.

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda would like to take this up

**Comment by chandansgowda** [comment]
@Aarush-Acharya Let me know how you would go about it before raising the PR

**Comment by Aarush-Acharya** [comment]
Alright @chandansgowda  understood would share give me a while to think on it

**Comment by chandansgowda** [comment]
Hey @Aarush-Acharya 
I've worked on this. Will be raising a PR soon.

**Comment by Aarush-Acharya** [comment]
Alright understood
