### ISSUE TITLE
Implement UI to show scheduled discussions

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#97]
This is a new feature where the user can put up a scheduled discussion on the platform. The users interested in it can like it and will be allowed to join the room once it starts. So that the admin can have a rough estimate of how many people are interested in the discussion.

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda I would like to take this Up

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda I had a thought rather than liking can we make it to subscribing as if the user has subscribed then they will receive push notifications an hour prior to the scheduled time for the discussion

**Comment by chandansgowda** [comment]
@Aarush-Acharya Let's go with subscribe button only
