### ISSUE TITLE
Put profile screen button in app bar

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#98]
We will have to use the current profile screen button in the bottom bar to have a place for discussions page. So lets put our profile screen button to app bar with circle avatar.

**Comment by asare-21** [comment]
Hey there, can I work on this?

**Comment by chandansgowda** [comment]
Hey @asare-21 
You can take this up.

@ShivamMenda Since @asare-21 commented on the issue first, I will have to assign it to them. Please feel free to look into other issues. You can also raise issues and work on them.

**Comment by ShivamMenda** [comment]
Sure @chandansgowda Will look into the app and other issues.
