### ISSUE TITLE
Retry failed API requests 

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate#99]
Currently, if the API request is not a success, the loading indicator disappears. Lets try requesting the api for few times before showing an error.

**Comment by Aarush-Acharya** [comment]
alright I can take it up

**Comment by Aarush-Acharya** [comment]
Hey @chandansgowda is this done or going on

**Comment by chandansgowda** [comment]
Sure. I have assigned you @Aarush-Acharya

**Comment by ShamanthOP** [comment]
@chandansgowda I would like to take this up.
